[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
include_directory = "0.1.1"
lazy_static = "1.5.0"
markup = "0.15.0"
salvo = "0.79.0"
tokio = { version = "1.45.1", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
